from pathlib import Path

from docwright.registry import Registry

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ai-docgen — Project Status</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333;
  }}
  h1 {{ color: #1a1a2e; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th {{ background: #1a1a2e; color: white; padding: 10px 14px; text-align: left; }}
  td {{ padding: 10px 14px; border-bottom: 1px solid #eee; }}
  tr:hover td {{ background: #f9f9f9; }}
  .synced {{ color: #22863a; font-weight: 600; }}
  .stale {{ color: #cb2431; font-weight: 600; }}
  footer {{ margin-top: 40px; color: #999; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>ai-docgen — Project Status</h1>
<table>
  <thead><tr><th>Project</th><th>Status</th><th>Last Updated</th><th>Documents</th></tr></thead>
  <tbody>
{rows}
  </tbody>
</table>
<footer>Generated by ai-docgen</footer>
</body>
</html>
"""


def render_html_report(registry_path: Path, output_path: Path) -> None:
    registry = Registry(registry_path)
    projects = registry.all_projects()
    rows: list[str] = []
    for project in projects:
        doc_links = ", ".join(f'<a href="{d.target}">{d.target}</a>' for d in project.documents)
        rows.append(
            f"    <tr>"
            f"<td>{project.name}</td>"
            f'<td class="{project.status}">{project.status}</td>'
            f"<td>{project.last_updated}</td>"
            f"<td>{doc_links}</td>"
            f"</tr>"
        )
    output_path.write_text(HTML_TEMPLATE.format(rows="\n".join(rows)))
